### ISSUE TITLE
Greedy Regex

### ISSUE THREAD

**Issue by dgwaldo** [WSDOT-GIS/CSV-Reader#5]
The regex in [getXYFieldNames] is a bit greedy. 

```javascript
xRegex = /(x)|(?:long(?:itude)?)/i;
yRegex = /(y)|(?:lat(?:itude)?)/i;
```

Maybe this would be better.

```javascript
xRegex = /(^[x])|(?:long(?:itude)?)/i;
yRegex = /(^[y])|(?:lat(?:itude)?)/i;
```

Your regex was matching `Y` on this field.
`SURVEY_META_ID`

This caused the geometry x & y to be null.

[getXYFieldNames]:https://github.com/WSDOT-GIS/CSV-Reader/blob/eda2800ab4a6c7044ce6553e91c615d867f2ae1e/csvArcGis.js#L85

Edit: Added formatting and link to function

**Comment by JeffJacobson** [comment]
It might be a while before I can get to this. If you want, you can fix this issue in a pull request. (See https://help.github.com/articles/github-flow/)

I haven't tested it, but this may work to fix the issue.
```javascript
xRegex = /^((x)|(?:long(?:itude)?))$/i;
yRegex = /^((y)|(?:lat(?:itude)?))$/i;
```
